//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarvestTimeTracking
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Project { get; set; }
        public Nullable<int> Project_Code { get; set; }
        public string Task { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Note { get; set; }
        public Nullable<double> Hours_rounded { get; set; }
        public string Invoiced { get; set; }
        public string Approved { get; set; }
        public string Department { get; set; }
        public string Billable { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
