//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pool_passes
    {
        public string Member_Name { get; set; }
        public string Member_Address { get; set; }
        public string CityStateZip { get; set; }
        public string Neighborhood { get; set; }
        public string Member_Email { get; set; }
        public string Member_Phone { get; set; }
        public Nullable<System.DateTime> Date_Application_Mailed_2009 { get; set; }
        public Nullable<decimal> Renewal_Price { get; set; }
        public Nullable<double> Number_of_Passess_Issued_2009 { get; set; }
        public string Pass_Assignees_2009 { get; set; }
        public bool Previous_Member { get; set; }
        public string Notes_2009 { get; set; }
        public Nullable<decimal> Amount_Paid_2009 { get; set; }
        public Nullable<System.DateTime> Date_Paid_2009 { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
    }
}
