//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageEdgeEncryptionProvider
    {
        public string Name { get; set; }
        public string AssemblyName { get; set; }
        public string ClassName { get; set; }
        public string EncryptionKey { get; set; }
        public int EncryptionKeySize { get; set; }
    }
}
