//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageEdgeBlob
    {
        public System.Guid BlobId { get; set; }
        public System.Guid SiteId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long Size { get; set; }
        public string Tier { get; set; }
        public bool InRBS { get; set; }
        public string BlobLocation { get; set; }
        public string BlobFileName { get; set; }
        public string FilterPending { get; set; }
    }
}
