//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageEdgeLocation
    {
        public System.Guid ScopeId { get; set; }
        public string Location { get; set; }
        public string Tier { get; set; }
        public long BlobCount { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
