//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAddendum
    {
        public tbAddendum()
        {
            this.tbAddendumSubTypes = new HashSet<tbAddendumSubType>();
        }
    
        public int AddendumID { get; set; }
        public string Addendum_Description { get; set; }
    
        public virtual ICollection<tbAddendumSubType> tbAddendumSubTypes { get; set; }
    }
}
