//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBillingData
    {
        public int BillingDataId { get; set; }
        public int ClientID { get; set; }
        public string AssessmentYear { get; set; }
        public Nullable<decimal> AssessmentAmount { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public Nullable<int> BillingFrequencyID { get; set; }
        public string DueDates { get; set; }
        public bool BilledByCOS { get; set; }
        public Nullable<decimal> LateFee { get; set; }
        public decimal LateDate { get; set; }
        public Nullable<double> Interest { get; set; }
        public bool SignedResolution { get; set; }
        public bool SetupinCinc { get; set; }
        public Nullable<System.DateTime> BillingGenerated { get; set; }
        public string InsertBy { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    
        public virtual tbAssessmentType tbAssessmentType { get; set; }
        public virtual tbBillingFrequency tbBillingFrequency { get; set; }
        public virtual tbClient tbClient { get; set; }
    }
}
