//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientPM
    {
        public int pmID { get; set; }
        public int clientID { get; set; }
        public double commission { get; set; }
        public System.DateTime datecreated { get; set; }
    }
}
