//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientPoolFee
    {
        public tbClientPoolFee()
        {
            this.tbMemberships = new HashSet<tbMembership>();
        }
    
        public int ClientPoolFeesID { get; set; }
        public int ClientID { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string description { get; set; }
        public int Cal_Year { get; set; }
    
        public virtual ICollection<tbMembership> tbMemberships { get; set; }
    }
}
