//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientManagementData
    {
        public int ClientManagementDataId { get; set; }
        public int ClientID { get; set; }
        public string AnnualMeetingMonth { get; set; }
        public string NoticeRequired { get; set; }
        public string QuorumRequired { get; set; }
        public string NoQuorumMetNewMtg { get; set; }
        public string QuorumNotMetNewMtgDate { get; set; }
        public string QuorumNotMetNewNotice { get; set; }
        public string QuorumNotMetNewQuorum { get; set; }
        public string TotalBoardMembers { get; set; }
        public bool StaggeredTerms { get; set; }
        public bool BudgetRatRequired { get; set; }
        public string InsertBy { get; set; }
        public System.DateTime InsertTime { get; set; }
        public string UpdateBy { get; set; }
        public byte[] UpdateTime { get; set; }
    
        public virtual tbClient tbClient { get; set; }
    }
}
