//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExpenseItem
    {
        public int InvoiceItemID { get; set; }
        public int ClientID { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Extended_Price { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public bool Exported { get; set; }
        public Nullable<System.DateTime> Exported_On { get; set; }
        public string logon_user { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> BatchID { get; set; }
    }
}
