//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMember
    {
        public tbMember()
        {
            this.tbMemberships = new HashSet<tbMembership>();
        }
    
        public int MemberID { get; set; }
        public string FamilyName { get; set; }
        public string email { get; set; }
        public string emergency_phone { get; set; }
        public string emergency_contact { get; set; }
        public string address { get; set; }
        public string csz { get; set; }
        public string neighborhood { get; set; }
        public Nullable<int> clientID { get; set; }
        public string referer { get; set; }
    
        public virtual tbClient tbClient { get; set; }
        public virtual ICollection<tbMembership> tbMemberships { get; set; }
    }
}
