//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPoolMember
    {
        public int PoolMemberID { get; set; }
        public string familyname { get; set; }
        public string adult1 { get; set; }
        public string adult2 { get; set; }
        public string child1 { get; set; }
        public string child2 { get; set; }
        public string child3 { get; set; }
        public string child4 { get; set; }
        public string child5 { get; set; }
        public string email { get; set; }
        public bool previous_member { get; set; }
        public string emergency_phone { get; set; }
        public bool pooltag_appln_rcvd { get; set; }
        public string indem_waiver_rcvd { get; set; }
        public string address { get; set; }
        public string csz { get; set; }
        public string neighborhood { get; set; }
        public Nullable<decimal> prev_amount_paid { get; set; }
        public Nullable<decimal> amount_paid { get; set; }
        public Nullable<System.DateTime> date_paid { get; set; }
        public string check_no { get; set; }
        public string note { get; set; }
        public Nullable<int> num_passes { get; set; }
        public Nullable<int> cal_year { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<System.DateTime> appln_mailed { get; set; }
        public bool mail_merge_exported { get; set; }
        public bool lifeguard_exported { get; set; }
        public int statusID { get; set; }
        public int membership_plan { get; set; }
        public string newmember { get; set; }
        public string referer { get; set; }
    }
}
