//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPoolPasses_
    {
        public string familyname { get; set; }
        public string email { get; set; }
        public bool previous_member { get; set; }
        public string emergency_phone { get; set; }
        public string address { get; set; }
        public string csz { get; set; }
        public Nullable<decimal> renewal_price { get; set; }
        public Nullable<double> cal_year { get; set; }
        public Nullable<double> clientID { get; set; }
    }
}
