//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServiceType
    {
        public tbServiceType()
        {
            this.tbClientContracts = new HashSet<tbClientContract>();
        }
    
        public int ServiceTypeID { get; set; }
        public string ServiceDescription { get; set; }
        public string Description { get; set; }
        public System.DateTime datecreated { get; set; }
    
        public virtual ICollection<tbClientContract> tbClientContracts { get; set; }
    }
}
