//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time_Detail
    {
        public int ID { get; set; }
        public Nullable<int> Association_ID { get; set; }
        public Nullable<System.DateTime> Event_Date { get; set; }
        public Nullable<int> Mgr_Name { get; set; }
        public Nullable<double> Mgr_Time_In { get; set; }
        public Nullable<double> Mgr_Time_out { get; set; }
        public Nullable<double> Mgr_Time_Mtg { get; set; }
        public Nullable<int> Total_Css_Tickets { get; set; }
        public Nullable<int> Total_Calls { get; set; }
        public Nullable<double> Total_Call_Time { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
